### ISSUE TITLE
start run Game_Entryoint crash ,how can i build shader bin?

### ISSUE THREAD

**Issue by yingnierxiao** [wobbier/MitchEngine#34]
![2024 06 24_郑捷 989e19d710da854a24e4e643991c5267](https://github.com/wobbier/MitchEngine/assets/3435706/9fa29822-67f4-49e6-9926-a71c7e0ac19e)

G:\gameEng\MyMitch\.build\game_win64_debug\Game_EntryPoint.exe
[Info]: Starting the MitchEngine.
[Info]: [File IO] Loaded File: Assets/Config/Engine.cfg
[Info]: [File IO] Loaded File: .tmp/MetadataCache.json
[Info]: [File IO] Loaded File: Assets/Shaders/UI.vert.meta
异常: Exception 0x80000003 encountered at address 0x7ff7cee55a96

**Comment by wobbier** [comment]
Hey!
I would build and run the "Editor" first and run it once, I don't think I support on-the-fly shader compiling for the game project.
but perhaps there's another issue on hand

**Comment by wobbier** [comment]
Also I'm not sure if you've pulled this repo itself, or used the project setup script.

https://github.com/wobbier/MitchEngine/blob/master/Tools/NewProjectSetup.bat 

New projects have use this atm, so put that into an empty folder and run it to set up a game project
